### ISSUE TITLE
ESPHome encoding

### ISSUE THREAD

**Issue by jasonmhite** [elementcarbon12/vornado_transom_remote_test#1]
Hello, thanks for this repository it was extremely useful. I wanted to take what you have found and translate it into the data format needed for ESPHome's [remote transmitter](https://esphome.io/components/remote_transmitter.html). I made up the following little Python snippet, which will convert the commands you discovered into the raw pulse lengths that ESPHome takes:

```python
def command2esphome(cmd: int) -> str:
    bit_seq = [
        (1260, -400) if c == "1" else (400, -1260)
        for c in f"{cmd:0>12b}"
    ]
    
    return "[" + ", ".join([str(item) for tup in bit_seq for item in tup]) + "]"
```

Then something like `print(command2esphome(0xD84))` will give you the string you can copy paste into ESPHome. In ESPHome a command can be sent with a button with something like this snippet:

```yaml
button:
  - platform: template
    name: Wake Display
    id: wake_display
    internal: true
    on_press:
      then:
      - remote_transmitter.transmit_raw: # 0xDDD
          code: [ 1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 1260, -400 ]
          repeat:
            times: 9
            wait_time: 7 ms
          carrier_frequency: 38000 Hz

  - platform: template
    name: Power Button
    id: vent_power
    internal: true
    on_press:
      then:
      - remote_transmitter.transmit_raw: # 0xD84
          code: [ 1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 400, -1260, 400, -1260, 400, -1260, 400, -1260, 1260, -400, 400, -1260, 400, -1260 ]
          repeat:
            times: 9
            wait_time: 7 ms
          carrier_frequency: 38000 Hz
```

I found repeating 9 times with 7 ms gap seems to work best and that seems to be how many times the physical remote sends them after hooking a logic analyzer to the LED. You also need the carrier frequency set to 38 kHz, as by default the `transmit_raw` function doesn't use modulation and just transmits direct pulse lengths. You also set `carrier_duty_percent: 50%` when setting up the `remote_transmitter` component (see the ESPHome docs for an explanation; tldr is that's the value for IR LEDs).

 For whatever reason, ESPHome doesn't seem to let you map a sequence of commands to a single button entity, but you need to send the no-op wake display command and then whatever command you want to get it to work reliably. But you can put them in a `script` with something like a 30 ms gap seems to work:

```yaml
script:
  - id: toggle_power
    then:
      - button.press: wake_display
      - delay: 30 ms
      - button.press: power_button
```

A basic example with a `switch` if you want to control the power (which was my goal, I don't really care about controlling the other functions for my use):

```yaml
switch:
  - platform: template
    name: Vent Fan
    restore_mode: DISABLED # otherwise ESPHome might toggle the switch at startup
    optimistic: True # important, assume switch switches when it's called
    turn_on_action:
      then:
        - script.execute: toggle_power
    turn_off_action:
      then:
        - script.execute: toggle_power
```

Note that you'll have to take some care to keep the fan state in sync but for my purposes this works well enough.

To save anybody the hassle, commands are:

* Wake screen/no-op [0xDDD]: `[1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 1260, -400]`
* Power button (center) [0xD84]: `[1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 1260, -400]`
* Toggle airflow direction (top) [0xD81]: `[1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 400, -1260, 400, -1260, 400, -1260, 400, -1260, 400, -1260, 400, -1260, 1260, -400]`
* Temp control button (bottom) [0xDC3]: `[1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 400, -1260, 400, -1260, 400, -1260, 1260, -400, 1260, -400]`
* Down (left) [0xDC6]: `[1260, -400, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 400, -1260, 400, -1260, 1260, -400, 1260, -400, 400, -1260]`
* Up (right) [0xD82]: `[1260, -400, 1260, -400, 400, -1260, 1260, -400, 400, -1260, 1260, -400, 1260, -400, 1260, -400, 400, -1260, 400, -1260, 1260, -400, 400, -1260]`

Note I only actually tested no-op and power, and took the rest from your Arduino sketch.
